services:
  backend:
    image: php:8.1-apache
    volumes: ./backend:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
  frontend:
    image: node:18
    command: npm run start
    volumes: ./frontend:/app